### ISSUE TITLE
WithPositional in documentation should be changed to WithUnnamed

### ISSUE THREAD

**Issue by Lockszmith-GH** [appccelerate/commandlineparser#1]
http://www.appccelerate.com/commandlineparser.html page described and demonstrates with code referring to 'WithPositional' that will fail compilation.

**Comment by ursenzler** [comment]
I renamed that to Positional. Are you using the latest package from nuget?

**Comment by ursenzler** [comment]
Oh! You are right. the documentation is updated, but the release on nuget is not. 

I'll update the release as soon as possible.

Thanks for reporting.

**Comment by ursenzler** [comment]
Please update the package to the latest version and Replace Unnamed with Positional.

**Comment by Lockszmith-GH** [comment]
Thanks, I will do that!

**Comment by Lockszmith-GH** [comment]
Works! thanks - great lib!

**Comment by ursenzler** [comment]
Thanks. 

If you have ideas for improvement, please let me know, or open a pull request. The lib is still very young.
